<?php
/**
 * Plugin Name: Manage & Resolve — Website Connector
 * Description: Connects WordPress to the Manage & Resolve website: stores dispute submissions, enquiries, training enquiries, newsletter subscribers and paid consultation bookings (each with a status workflow), and refreshes the website when blog posts change. Settings → Manage & Resolve has the setup checklist.
 * Version: 1.2.0
 * Requires at least: 6.3
 * Requires PHP: 7.4
 * Author: Manage & Resolve
 *
 * The website sends entries to POST /wp-json/mr/v1/submissions/{type}, authenticated with an
 * Application Password belonging to a user with the "Website forms (API only)" role.
 * Entries are private: never public, never readable through the public REST API.
 *
 * Configure in Settings → Manage & Resolve (includes/settings.php): website address, refresh
 * secret, notification emails. Consultation bookings live in includes/bookings.php; the blog
 * refresh ping in includes/revalidate.php.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class MR_Submissions {

	const VERSION        = '1.2.0';
	const SUBMIT_CAP     = 'submit_mr_entries';
	const SUBMITTER_ROLE = 'mr_website_forms';
	const META           = '_mr_';
	const NONCE          = 'mr_entry_meta';

	/** Capabilities generated by capability_type => mr_entry / mr_entries. */
	const MANAGE_CAPS = array(
		'edit_mr_entries',
		'edit_others_mr_entries',
		'edit_private_mr_entries',
		'edit_published_mr_entries',
		'read_private_mr_entries',
		'publish_mr_entries',
		'delete_mr_entries',
		'delete_others_mr_entries',
		'delete_private_mr_entries',
		'delete_published_mr_entries',
	);

	/**
	 * Entry types. `fields` mirror the website's validation rules (lib/forms.ts):
	 * label, max length, required, kind (text | email | textarea).
	 */
	public static function types() {
		$workflow = array(
			'new'       => 'New',
			'in_review' => 'In review',
			'contacted' => 'Contacted',
			'closed'    => 'Closed',
		);

		return array(
			// Created by includes/bookings.php (hold → paid), not by the submissions endpoint.
			'booking'    => array(
				'post_type' => 'mr_booking',
				'plural'    => 'Consultations',
				'singular'  => 'Consultation',
				'icon'      => 'dashicons-calendar-alt',
				'position'  => 25,
				'title'     => array( 'name', 'when' ),
				'columns'   => array( 'when', 'email', 'phone', 'amount' ),
				'statuses'  => array(
					'pending_payment' => 'Awaiting payment',
					'confirmed'       => 'Confirmed',
					'needs_attention' => 'Needs attention',
					'completed'       => 'Completed',
					'cancelled'       => 'Cancelled',
					'refunded'        => 'Refunded',
					'expired'         => 'Expired (unpaid)',
				),
				'notify'    => null,
				'private'   => array(),
				'fields'    => array(
					'when'      => array( 'Consultation time', 100, false, 'text' ),
					'name'      => array( 'Name', 200, true, 'text' ),
					'email'     => array( 'Email', 254, true, 'email' ),
					'phone'     => array( 'Phone', 30, true, 'text' ),
					'company'   => array( 'Company / organisation', 200, false, 'text' ),
					'topic'     => array( 'What they would like to discuss', 2000, false, 'textarea' ),
					'amount'    => array( 'Amount', 50, false, 'text' ),
					'reference' => array( 'Payment reference', 100, false, 'text' ),
					'paid_at'   => array( 'Paid at', 100, false, 'text' ),
				),
			),
			'dispute'    => array(
				'post_type' => 'mr_dispute',
				'plural'    => 'Disputes',
				'singular'  => 'Dispute',
				'icon'      => 'dashicons-shield',
				'position'  => 26,
				'title'     => array( 'name', 'nature' ),
				'columns'   => array( 'email', 'phone', 'nature', 'urgency' ),
				'statuses'  => $workflow,
				'notify'    => 'notify_disputes',
				// Never emailed — dispute details stay inside WordPress.
				'private'   => array( 'details' ),
				'fields'    => array(
					'name'       => array( 'Name', 200, true, 'text' ),
					'email'      => array( 'Email', 254, true, 'email' ),
					'phone'      => array( 'Phone', 30, true, 'text' ),
					'company'    => array( 'Company / organisation', 200, false, 'text' ),
					'otherParty' => array( 'Other party', 300, true, 'text' ),
					'nature'     => array( 'Nature of the dispute', 100, true, 'text' ),
					'method'     => array( 'Preferred resolution method', 100, false, 'text' ),
					'details'    => array( 'About the dispute', 10000, true, 'textarea' ),
					'value'      => array( 'Estimated dispute value', 100, false, 'text' ),
					'urgency'    => array( 'Urgency', 100, false, 'text' ),
					'referral'   => array( 'How they found us', 100, false, 'text' ),
				),
			),
			'contact'    => array(
				'post_type' => 'mr_enquiry',
				'plural'    => 'Enquiries',
				'singular'  => 'Enquiry',
				'icon'      => 'dashicons-email-alt',
				'position'  => 27,
				'title'     => array( 'name', 'subject' ),
				'columns'   => array( 'email', 'phone', 'subject' ),
				'statuses'  => $workflow,
				'notify'    => 'notify_enquiries',
				'private'   => array(),
				'fields'    => array(
					'name'    => array( 'Name', 200, true, 'text' ),
					'email'   => array( 'Email', 254, true, 'email' ),
					'phone'   => array( 'Phone', 30, false, 'text' ),
					'subject' => array( 'Subject', 100, true, 'text' ),
					'message' => array( 'Message', 5000, true, 'textarea' ),
				),
			),
			'training'   => array(
				'post_type' => 'mr_training_enquiry',
				'plural'    => 'Training Enquiries',
				'singular'  => 'Training Enquiry',
				'icon'      => 'dashicons-welcome-learn-more',
				'position'  => 28,
				'title'     => array( 'name', 'programme' ),
				'columns'   => array( 'email', 'programme', 'request', 'participants' ),
				'statuses'  => $workflow,
				'notify'    => 'notify_enquiries',
				'private'   => array(),
				'fields'    => array(
					'name'         => array( 'Name', 200, true, 'text' ),
					'email'        => array( 'Email', 254, true, 'email' ),
					'phone'        => array( 'Phone', 30, false, 'text' ),
					'organisation' => array( 'Company / organisation', 200, false, 'text' ),
					'programme'    => array( 'Programme', 100, true, 'text' ),
					'request'      => array( 'Request', 100, true, 'text' ),
					'format'       => array( 'Preferred format', 100, false, 'text' ),
					'participants' => array( 'Participants', 100, false, 'text' ),
					'message'      => array( 'Message', 5000, false, 'textarea' ),
				),
			),
			'newsletter' => array(
				'post_type' => 'mr_subscriber',
				'plural'    => 'Subscribers',
				'singular'  => 'Subscriber',
				'icon'      => 'dashicons-megaphone',
				'position'  => 29,
				'title'     => array( 'email' ),
				'columns'   => array( 'firstName' ),
				'statuses'  => array(
					'subscribed'   => 'Subscribed',
					'unsubscribed' => 'Unsubscribed',
				),
				'notify'    => null,
				'private'   => array(),
				'fields'    => array(
					'firstName' => array( 'First name', 100, false, 'text' ),
					'email'     => array( 'Email', 254, true, 'email' ),
				),
			),
		);
	}

	public static function init() {
		add_action( 'init', array( __CLASS__, 'register_post_types' ) );
		add_action( 'init', array( __CLASS__, 'maybe_install' ) );
		add_action( 'rest_api_init', array( __CLASS__, 'register_routes' ) );

		if ( is_admin() ) {
			add_action( 'add_meta_boxes', array( __CLASS__, 'add_meta_boxes' ) );
			add_action( 'save_post', array( __CLASS__, 'save_meta_box' ), 10, 2 );
			add_action( 'restrict_manage_posts', array( __CLASS__, 'status_filter' ) );
			add_action( 'pre_get_posts', array( __CLASS__, 'apply_status_filter' ) );
			add_filter( 'post_row_actions', array( __CLASS__, 'row_actions' ), 10, 2 );
			add_filter( 'display_post_states', array( __CLASS__, 'post_states' ), 10, 2 );
			add_action( 'admin_post_mr_export_subscribers', array( __CLASS__, 'export_subscribers' ) );

			foreach ( self::types() as $type ) {
				$post_type = $type['post_type'];
				add_filter( "manage_{$post_type}_posts_columns", array( __CLASS__, 'list_columns' ) );
				add_action( "manage_{$post_type}_posts_custom_column", array( __CLASS__, 'list_column_value' ), 10, 2 );
			}
		}
	}

	// ---------------------------------------------------------------------------
	// Setup
	// ---------------------------------------------------------------------------

	public static function register_post_types() {
		foreach ( self::types() as $type ) {
			register_post_type(
				$type['post_type'],
				array(
					'labels'              => array(
						'name'               => $type['plural'],
						'singular_name'      => $type['singular'],
						'menu_name'          => $type['plural'],
						'all_items'          => 'All ' . strtolower( $type['plural'] ),
						'edit_item'          => 'View ' . strtolower( $type['singular'] ),
						'search_items'       => 'Search ' . strtolower( $type['plural'] ),
						'not_found'          => 'Nothing here yet.',
						'not_found_in_trash' => 'Nothing in the bin.',
					),
					'public'              => false,
					'show_ui'             => true,
					'show_in_menu'        => true,
					'show_in_rest'        => false,
					'exclude_from_search' => true,
					'publicly_queryable'  => false,
					'has_archive'         => false,
					'rewrite'             => false,
					'query_var'           => false,
					'menu_icon'           => $type['icon'],
					'menu_position'       => $type['position'],
					'supports'            => array( 'title' ),
					'capability_type'     => array( 'mr_entry', 'mr_entries' ),
					'map_meta_cap'        => true,
					// Entries only ever arrive from the website.
					'capabilities'        => array( 'create_posts' => 'do_not_allow' ),
				)
			);
		}
	}

	/** Grants capabilities and creates the API-only role (re-runs when the version changes). */
	public static function maybe_install() {
		if ( get_option( 'mr_submissions_version' ) === self::VERSION ) {
			return;
		}

		$admin = get_role( 'administrator' );
		if ( $admin ) {
			foreach ( self::MANAGE_CAPS as $cap ) {
				$admin->add_cap( $cap );
			}
		}

		if ( ! get_role( self::SUBMITTER_ROLE ) ) {
			add_role( self::SUBMITTER_ROLE, 'Website forms (API only)', array( 'read' => true ) );
		}
		get_role( self::SUBMITTER_ROLE )->add_cap( self::SUBMIT_CAP );

		update_option( 'mr_submissions_version', self::VERSION );
	}

	private static function type_for_post_type( $post_type ) {
		foreach ( self::types() as $key => $type ) {
			if ( $type['post_type'] === $post_type ) {
				return array( $key, $type );
			}
		}
		return array( null, null );
	}

	private static function meta( $post_id, $field ) {
		return (string) get_post_meta( $post_id, self::META . $field, true );
	}

	// ---------------------------------------------------------------------------
	// REST API — POST /wp-json/mr/v1/submissions/{type}
	// ---------------------------------------------------------------------------

	public static function register_routes() {
		register_rest_route(
			'mr/v1',
			'/submissions/(?P<type>dispute|contact|training|newsletter)',
			array(
				'methods'             => 'POST',
				'callback'            => array( __CLASS__, 'handle_submission' ),
				'permission_callback' => function () {
					return current_user_can( self::SUBMIT_CAP );
				},
			)
		);
	}

	public static function handle_submission( WP_REST_Request $request ) {
		$types  = self::types();
		$key    = $request['type'];
		$type   = $types[ $key ];
		$params = $request->get_json_params();
		$params = is_array( $params ) ? $params : array();

		$values = array();
		$errors = array();

		foreach ( $type['fields'] as $field => $definition ) {
			list( , $max, $required, $kind ) = $definition;
			$raw = isset( $params[ $field ] ) && is_scalar( $params[ $field ] ) ? (string) $params[ $field ] : '';

			if ( 'textarea' === $kind ) {
				$value = sanitize_textarea_field( $raw );
			} elseif ( 'email' === $kind ) {
				$value = sanitize_email( $raw );
			} else {
				$value = sanitize_text_field( $raw );
			}
			$value = mb_substr( trim( $value ), 0, $max );

			if ( $required && '' === $value ) {
				$errors[ $field ] = 'This field is required.';
			} elseif ( 'email' === $kind && '' !== $value && ! is_email( $value ) ) {
				$errors[ $field ] = 'Please enter a valid email address.';
			}
			$values[ $field ] = $value;
		}

		if ( $errors ) {
			return new WP_Error( 'mr_invalid', 'Some fields are invalid.', array( 'status' => 422, 'errors' => $errors ) );
		}

		// Newsletter: one entry per email address — re-subscribing updates it.
		if ( 'newsletter' === $key ) {
			$existing = get_posts(
				array(
					'post_type'      => $type['post_type'],
					'post_status'    => 'any',
					'posts_per_page' => 1,
					'fields'         => 'ids',
					'meta_key'       => self::META . 'email',
					'meta_value'     => $values['email'],
				)
			);
			if ( $existing ) {
				if ( '' !== $values['firstName'] ) {
					update_post_meta( $existing[0], self::META . 'firstName', $values['firstName'] );
				}
				update_post_meta( $existing[0], self::META . 'status', 'subscribed' );
				return new WP_REST_Response( array( 'ok' => true, 'id' => $existing[0], 'existing' => true ), 200 );
			}
		}

		$title_parts = array();
		foreach ( $type['title'] as $field ) {
			if ( '' !== $values[ $field ] ) {
				$title_parts[] = $values[ $field ];
			}
		}

		$post_id = wp_insert_post(
			array(
				'post_type'   => $type['post_type'],
				'post_status' => 'private',
				'post_title'  => implode( ' — ', $title_parts ),
			),
			true
		);
		if ( is_wp_error( $post_id ) ) {
			return new WP_Error( 'mr_save_failed', 'The entry could not be saved.', array( 'status' => 500 ) );
		}

		foreach ( $values as $field => $value ) {
			update_post_meta( $post_id, self::META . $field, $value );
		}
		update_post_meta( $post_id, self::META . 'status', array_key_first( $type['statuses'] ) );

		self::notify( $key, $type, $post_id, $values );

		return new WP_REST_Response( array( 'ok' => true, 'id' => $post_id ), 201 );
	}

	/** Emails the team. A failed email never fails the submission. */
	private static function notify( $key, $type, $post_id, $values ) {
		if ( empty( $type['notify'] ) ) {
			return;
		}
		$to = MR_Settings::notify_email( $type['notify'] );

		$lines = array( 'A new ' . strtolower( $type['singular'] ) . ' has arrived from the website.', '' );
		foreach ( $type['fields'] as $field => $definition ) {
			if ( in_array( $field, $type['private'], true ) || '' === $values[ $field ] ) {
				continue;
			}
			$lines[] = $definition[0] . ': ' . $values[ $field ];
		}
		if ( $type['private'] ) {
			$lines[] = '';
			$lines[] = 'For confidentiality, the full details are only available inside WordPress.';
		}
		$lines[] = '';
		$lines[] = 'Open it: ' . admin_url( 'post.php?post=' . $post_id . '&action=edit' );

		$reply_to = is_email( $values['email'] ?? '' ) ? array( 'Reply-To: ' . $values['email'] ) : array();
		// Raw title: get_the_title() would prefix "Private:".
		wp_mail( $to, 'New ' . strtolower( $type['singular'] ) . ': ' . get_post_field( 'post_title', $post_id ), implode( "\n", $lines ), $reply_to );
	}

	// ---------------------------------------------------------------------------
	// Admin — list screens
	// ---------------------------------------------------------------------------

	public static function list_columns( $columns ) {
		list( $key, $type ) = self::type_for_post_type( get_current_screen()->post_type );
		$result             = array(
			'cb'    => $columns['cb'],
			'title' => 'newsletter' === $key ? 'Email' : 'Entry',
		);
		foreach ( $type['columns'] as $field ) {
			$result[ 'mr_' . $field ] = $type['fields'][ $field ][0];
		}
		$result['mr_status']   = 'Status';
		// Own column: WordPress labels private posts' dates "Last Modified".
		$result['mr_received'] = 'Received';
		return $result;
	}

	public static function list_column_value( $column, $post_id ) {
		if ( 0 !== strpos( $column, 'mr_' ) ) {
			return;
		}
		$field = substr( $column, 3 );
		if ( 'received' === $field ) {
			echo esc_html( get_the_date( 'j M Y, g:i a', $post_id ) );
			return;
		}
		if ( 'status' === $field ) {
			list( , $type ) = self::type_for_post_type( get_post_type( $post_id ) );
			$status         = self::meta( $post_id, 'status' );
			echo esc_html( $type['statuses'][ $status ] ?? $status );
			return;
		}
		echo esc_html( self::meta( $post_id, $field ) );
	}

	public static function status_filter( $post_type ) {
		list( $key, $type ) = self::type_for_post_type( $post_type );
		if ( ! $type ) {
			return;
		}
		$current = isset( $_GET['mr_status'] ) ? sanitize_key( wp_unslash( $_GET['mr_status'] ) ) : '';
		echo '<select name="mr_status"><option value="">All statuses</option>';
		foreach ( $type['statuses'] as $value => $label ) {
			printf( '<option value="%s"%s>%s</option>', esc_attr( $value ), selected( $current, $value, false ), esc_html( $label ) );
		}
		echo '</select>';

		if ( 'newsletter' === $key && current_user_can( 'edit_others_mr_entries' ) ) {
			$url = wp_nonce_url( admin_url( 'admin-post.php?action=mr_export_subscribers' ), 'mr_export_subscribers' );
			printf( ' <a class="button" href="%s">Export CSV</a>', esc_url( $url ) );
		}
	}

	public static function apply_status_filter( $query ) {
		if ( ! $query->is_main_query() || empty( $_GET['mr_status'] ) ) {
			return;
		}
		list( , $type ) = self::type_for_post_type( $query->get( 'post_type' ) );
		if ( $type ) {
			$query->set( 'meta_key', self::META . 'status' );
			$query->set( 'meta_value', sanitize_key( wp_unslash( $_GET['mr_status'] ) ) );
		}
	}

	/** No Quick Edit — it would expose post status/visibility controls that don't apply here. */
	public static function row_actions( $actions, $post ) {
		list( , $type ) = self::type_for_post_type( $post->post_type );
		if ( $type ) {
			unset( $actions['inline hide-if-no-js'] );
			if ( isset( $actions['edit'] ) ) {
				$actions['edit'] = str_replace( '>Edit<', '>View<', $actions['edit'] );
			}
		}
		return $actions;
	}

	/** Every entry is private, so the "— Private" label on each row is noise. */
	public static function post_states( $states, $post ) {
		list( , $type ) = self::type_for_post_type( $post->post_type );
		if ( $type ) {
			unset( $states['private'] );
		}
		return $states;
	}

	public static function export_subscribers() {
		if ( ! current_user_can( 'edit_others_mr_entries' ) ) {
			wp_die( 'You are not allowed to export subscribers.', 403 );
		}
		check_admin_referer( 'mr_export_subscribers' );

		$ids = get_posts(
			array(
				'post_type'      => 'mr_subscriber',
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'fields'         => 'ids',
				'orderby'        => 'date',
				'order'          => 'ASC',
			)
		);

		nocache_headers();
		header( 'Content-Type: text/csv; charset=utf-8' );
		header( 'Content-Disposition: attachment; filename=dede-law-subscribers-' . gmdate( 'Y-m-d' ) . '.csv' );
		$out = fopen( 'php://output', 'w' );
		fputcsv( $out, array( 'Email', 'First name', 'Status', 'Subscribed on' ) );
		foreach ( $ids as $id ) {
			fputcsv( $out, array( self::meta( $id, 'email' ), self::meta( $id, 'firstName' ), self::meta( $id, 'status' ), get_the_date( 'Y-m-d', $id ) ) );
		}
		fclose( $out );
		exit;
	}

	// ---------------------------------------------------------------------------
	// Admin — entry screen
	// ---------------------------------------------------------------------------

	public static function add_meta_boxes( $post_type ) {
		list( , $type ) = self::type_for_post_type( $post_type );
		if ( ! $type ) {
			return;
		}
		add_meta_box( 'mr_entry_details', 'Submitted details', array( __CLASS__, 'render_details' ), $post_type, 'normal', 'high' );
		add_meta_box( 'mr_entry_workflow', 'Status &amp; notes', array( __CLASS__, 'render_workflow' ), $post_type, 'side', 'high' );
	}

	public static function render_details( $post ) {
		list( , $type ) = self::type_for_post_type( $post->post_type );
		echo '<table class="widefat striped"><tbody>';
		foreach ( $type['fields'] as $field => $definition ) {
			$value = self::meta( $post->ID, $field );
			if ( 'email' === $definition[3] && $value ) {
				$display = sprintf( '<a href="mailto:%1$s">%1$s</a>', esc_html( $value ) );
			} elseif ( 'textarea' === $definition[3] ) {
				$display = nl2br( esc_html( $value ) );
			} else {
				$display = esc_html( $value );
			}
			printf( '<tr><th style="width:30%%">%s</th><td>%s</td></tr>', esc_html( $definition[0] ), $display ? $display : '<span style="color:#999">—</span>' );
		}
		printf( '<tr><th>Received</th><td>%s</td></tr>', esc_html( get_the_date( 'j F Y, g:i a', $post ) ) );
		echo '</tbody></table>';
	}

	public static function render_workflow( $post ) {
		list( , $type ) = self::type_for_post_type( $post->post_type );
		wp_nonce_field( self::NONCE, self::NONCE );
		$status = self::meta( $post->ID, 'status' );

		echo '<p><label for="mr_status_field"><strong>Status</strong></label><br />';
		echo '<select id="mr_status_field" name="mr_status_field" style="width:100%">';
		foreach ( $type['statuses'] as $value => $label ) {
			printf( '<option value="%s"%s>%s</option>', esc_attr( $value ), selected( $status, $value, false ), esc_html( $label ) );
		}
		echo '</select></p>';

		echo '<p><label for="mr_notes_field"><strong>Internal notes</strong></label><br />';
		printf(
			'<textarea id="mr_notes_field" name="mr_notes_field" rows="6" style="width:100%%">%s</textarea></p>',
			esc_textarea( self::meta( $post->ID, 'notes' ) )
		);
		echo '<p class="description">Only visible to your team. Click Update to save.</p>';
	}

	public static function save_meta_box( $post_id, $post ) {
		list( , $type ) = self::type_for_post_type( $post->post_type );
		if ( ! $type || ! isset( $_POST[ self::NONCE ] ) ) {
			return;
		}
		if ( ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST[ self::NONCE ] ) ), self::NONCE ) ) {
			return;
		}
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}

		$status = isset( $_POST['mr_status_field'] ) ? sanitize_key( wp_unslash( $_POST['mr_status_field'] ) ) : '';
		if ( isset( $type['statuses'][ $status ] ) ) {
			update_post_meta( $post_id, self::META . 'status', $status );
		}
		if ( isset( $_POST['mr_notes_field'] ) ) {
			update_post_meta( $post_id, self::META . 'notes', sanitize_textarea_field( wp_unslash( $_POST['mr_notes_field'] ) ) );
		}
	}
}

MR_Submissions::init();

require_once __DIR__ . '/includes/settings.php';
require_once __DIR__ . '/includes/bookings.php';
require_once __DIR__ . '/includes/revalidate.php';
MR_Settings::init();
MR_Bookings::init();
MR_Revalidate::init();
